// BIST TÜM Hisseler - Tam Liste
export const BIST_STOCKS = [
  { symbol: 'A1CAP', name: 'A1 Capital Yatırım' },
  { symbol: 'ARASE', name: 'A1 Yenilenebilir Enerji' },
  { symbol: 'AGROT', name: 'Agrotech Yüksek Teknoloji' },
  { symbol: 'AGHOL', name: 'AG Anadolu Grubu Holding' },
  { symbol: 'AGYO', name: 'Atakule GYO' },
  { symbol: 'AHGAZ', name: 'Ahlatcı Doğalgaz' },
  { symbol: 'AHSGY', name: 'Ahes GYO' },
  { symbol: 'ACSEL', name: 'Acıselsan Acıpayam Selüloz' },
  { symbol: 'ADEL', name: 'Adel Kalemcilik' },
  { symbol: 'ADESE', name: 'Adese Gayrimenkul' },
  { symbol: 'ADGYO', name: 'Adra GYO' },
  { symbol: 'AEFES', name: 'Anadolu Efes' },
  { symbol: 'AFYON', name: 'Afyon Çimento' },
  { symbol: 'AGESA', name: 'AgeSA Hayat ve Emeklilik' },
  { symbol: 'AKBNK', name: 'Akbank' },
  { symbol: 'AKCNS', name: 'Akçansa Çimento' },
  { symbol: 'AKENR', name: 'Ak Enerji' },
  { symbol: 'AKFGY', name: 'Akfen GYO' },
  { symbol: 'AKFIN', name: 'Akfen İnşaat' },
  { symbol: 'AKFYE', name: 'Akfen Yenilenebilir Enerji' },
  { symbol: 'AKGRT', name: 'Aksigorta' },
  { symbol: 'AKHUN', name: 'Akhan Un Fabrikası' },
  { symbol: 'AKMGY', name: 'Akmerkez GYO' },
  { symbol: 'AKSA', name: 'Aksa Akrilik' },
  { symbol: 'AKSEN', name: 'Aksa Enerji' },
  { symbol: 'AKSGY', name: 'Akiş GYO' },
  { symbol: 'AKSUE', name: 'Aksu Enerji' },
  { symbol: 'AKYHO', name: 'Akdeniz Yatırım Holding' },
  { symbol: 'ALARK', name: 'Alarko Holding' },
  { symbol: 'ALBRK', name: 'Albaraka Türk' },
  { symbol: 'ALCAR', name: 'Alarko Carrier' },
  { symbol: 'ALCTL', name: 'Alcatel Lucent Teletaş' },
  { symbol: 'ALFAS', name: 'Alfa Solar Enerji' },
  { symbol: 'ALGYO', name: 'Alarko GYO' },
  { symbol: 'ALKA', name: 'Alkim Kağıt' },
  { symbol: 'ALKIM', name: 'Alkim Kimya' },
  { symbol: 'ALTKS', name: 'Altınkılıç Gıda' },
  { symbol: 'ALMAD', name: 'Ruzy Madencilik' },
  { symbol: 'ALTNM', name: 'Altınay Savunma' },
  { symbol: 'ALVES', name: 'Alves Kablo' },
  { symbol: 'ANELE', name: 'Anel Elektrik' },
  { symbol: 'ANATL', name: 'Anatolia Tanı' },
  { symbol: 'ANHYT', name: 'Anadolu Hayat Emeklilik' },
  { symbol: 'ANSGR', name: 'Anadolu Sigorta' },
  { symbol: 'ARASE', name: 'Doğu Aras Enerji' },
  { symbol: 'ARCLK', name: 'Arçelik' },
  { symbol: 'ARDYZ', name: 'ARD Grup Bilişim' },
  { symbol: 'ARENA', name: 'Arena Bilgisayar' },
  { symbol: 'ARFYO', name: 'ARF Bio Yenilenebilir' },
  { symbol: 'ARMDA', name: 'Armada Gıda' },
  { symbol: 'ARSAN', name: 'Arsan Holding' },
  { symbol: 'ARTMS', name: 'Artemis Halı' },
  { symbol: 'ARZUM', name: 'Arzum Ev Aletleri' },
  { symbol: 'ASELS', name: 'Aselsan' },
  { symbol: 'ASGYO', name: 'ASCE GYO' },
  { symbol: 'ASTOR', name: 'Astor Enerji' },
  { symbol: 'ASUZU', name: 'Anadolu Isuzu' },
  { symbol: 'ATAGY', name: 'ATA GYO' },
  { symbol: 'ATAKP', name: 'Atakey Patates' },
  { symbol: 'ATATP', name: 'ATP Yazılım' },
  { symbol: 'ATEKS', name: 'Ata Turizm' },
  { symbol: 'AVGYO', name: 'Avrasya GYO' },
  { symbol: 'AVHOL', name: 'Avrupa Yatırım Holding' },
  { symbol: 'AVOD', name: 'AVOD Kurutulmuş Gıda' },
  { symbol: 'AVPGY', name: 'Avrupakent GYO' },
  { symbol: 'AVTUR', name: 'Avrasya Petrol' },
  { symbol: 'AYCES', name: 'Altınyunus Çeşme' },
  { symbol: 'AYDEM', name: 'Aydem Enerji' },
  { symbol: 'AYEN', name: 'Ayen Enerji' },
  { symbol: 'AYGAZ', name: 'Aygaz' },
  { symbol: 'AZTEK', name: 'Aztek Teknoloji' },
  { symbol: 'BAGFS', name: 'Bagfaş' },
  { symbol: 'BAHKM', name: 'Bahadır Kimya' },
  { symbol: 'BAKAB', name: 'Bak Ambalaj' },
  { symbol: 'BALSU', name: 'Balsu Gıda' },
  { symbol: 'BANVT', name: 'Banvit' },
  { symbol: 'BAREM', name: 'Barem Ambalaj' },
  { symbol: 'BASCM', name: 'Başkent Doğalgaz GYO' },
  { symbol: 'BAYRK', name: 'Bayrak EBT' },
  { symbol: 'BEGYO', name: 'Batı Ege GYO' },
  { symbol: 'BERA', name: 'Bera Holding' },
  { symbol: 'BESLR', name: 'Besler Gıda' },
  { symbol: 'BESTB', name: 'Best Brands Enerji' },
  { symbol: 'BEYAZ', name: 'Beyaz Filo' },
  { symbol: 'BMSCH', name: 'Bosch Fren' },
  { symbol: 'BIENY', name: 'Bien Yapı' },
  { symbol: 'BIGCH', name: 'Bigchefs' },
  { symbol: 'BILGR', name: 'Birleşim Grup Enerji' },
  { symbol: 'BIGMT', name: 'Big Medya Teknoloji' },
  { symbol: 'BIMAS', name: 'BİM Mağazalar' },
  { symbol: 'BINUL', name: 'Bin Ulaşım' },
  { symbol: 'BINYT', name: '1000 Yatırımlar Holding' },
  { symbol: 'BIOEN', name: 'Biotrend Enerji' },
  { symbol: 'BIZIM', name: 'Bizim Toptan' },
  { symbol: 'BJKAS', name: 'Beşiktaş Futbol' },
  { symbol: 'BLCYT', name: 'Bilici Yatırım' },
  { symbol: 'BLUME', name: 'Blume Metal Kimya' },
  { symbol: 'BMSTL', name: 'BMS Çelik Hasır' },
  { symbol: 'BMSND', name: 'BMS Birleşik Metal' },
  { symbol: 'BNTAS', name: 'Bantaş Ambalaj' },
  { symbol: 'BOBET', name: 'Boğaziçi Beton' },
  { symbol: 'BORLS', name: 'Borlease Otomotiv' },
  { symbol: 'BORSK', name: 'Bor Şeker' },
  { symbol: 'BOSSA', name: 'Bossa' },
  { symbol: 'BRISA', name: 'Brisa' },
  { symbol: 'BRKVY', name: 'Berkosan Yalıtım' },
  { symbol: 'BRLSM', name: 'Birleşim Mühendislik' },
  { symbol: 'BRVKM', name: 'Birikim Varlık' },
  { symbol: 'BRSAN', name: 'Borusan Mannesmann' },
  { symbol: 'BRYAT', name: 'Borusan Yatırım' },
  { symbol: 'BSOKE', name: 'Batısöke Çimento' },
  { symbol: 'BTCIM', name: 'Batıçim' },
  { symbol: 'BUCIM', name: 'Bursa Çimento' },
  { symbol: 'BULLS', name: 'Bulls Girişim' },
  { symbol: 'BURCE', name: 'Burçelik' },
  { symbol: 'BURVA', name: 'Burçelik Vana' },
  { symbol: 'BVBLG', name: 'Bülbüloğlu Vinç' },
  { symbol: 'BYDNR', name: 'Baydöner' },
  { symbol: 'CANTE', name: 'Çan2 Termik' },
  { symbol: 'CATES', name: 'Çateş Elektrik' },
  { symbol: 'CCOLA', name: 'Coca-Cola İçecek' },
  { symbol: 'CELHA', name: 'Çelik Halat' },
  { symbol: 'CEMAS', name: 'Çemaş Döküm' },
  { symbol: 'CEMTS', name: 'Çemtaş' },
  { symbol: 'CEMZY', name: 'Cem Zeytin' },
  { symbol: 'CEOEM', name: 'CEO Event Medya' },
  { symbol: 'CGCAM', name: 'Çağdaş Cam' },
  { symbol: 'CIMSA', name: 'Çimsa' },
  { symbol: 'CLEBI', name: 'Çelebi Havacılık' },
  { symbol: 'CMBTN', name: 'Çimbeton' },
  { symbol: 'CONSE', name: 'Consus Enerji' },
  { symbol: 'COSMO', name: 'Cosmos Yatırım Holding' },
  { symbol: 'CRDFA', name: 'Creditwest Faktoring' },
  { symbol: 'CRFSA', name: 'CarrefourSA' },
  { symbol: 'CUHDR', name: 'Çuhadaroğlu Metal' },
  { symbol: 'CVKMD', name: 'CVK Maden' },
  { symbol: 'CWENE', name: 'CW Enerji' },
  { symbol: 'DAGI', name: 'Dagi Giyim' },
  { symbol: 'DAPGM', name: 'DAP Gayrimenkul' },
  { symbol: 'DARDL', name: 'Dardanel' },
  { symbol: 'DCTTR', name: 'DCT Trading' },
  { symbol: 'DENGE', name: 'Denge Yatırım Holding' },
  { symbol: 'DERLK', name: 'Derluks Yatırım Holding' },
  { symbol: 'DERIM', name: 'Derimod' },
  { symbol: 'DESA', name: 'Desa Deri' },
  { symbol: 'DESPC', name: 'Despec Bilgisayar' },
  { symbol: 'DEVA', name: 'Deva Holding' },
  { symbol: 'DGATE', name: 'Datagate Bilgisayar' },
  { symbol: 'DGGYO', name: 'Doğuş GYO' },
  { symbol: 'DGNMO', name: 'Doğanlar Mobilya' },
  { symbol: 'DITAS', name: 'Ditaş BDY' },
  { symbol: 'DMRGD', name: 'DMR Unlu Mamuller' },
  { symbol: 'DMSAS', name: 'Demisaş Döküm' },
  { symbol: 'DNISI', name: 'Dinamik Isı' },
  { symbol: 'DOAS', name: 'Doğuş Otomotiv' },
  { symbol: 'DOBUR', name: 'Do&Co' },
  { symbol: 'DOCO', name: 'Do&Co AG' },
  { symbol: 'DOFER', name: 'Dofer Yapı' },
  { symbol: 'DOFRT', name: 'DOF Robotik' },
  { symbol: 'DOGUB', name: 'Doğusan Boru' },
  { symbol: 'DOHOL', name: 'Doğan Holding' },
  { symbol: 'DOKTA', name: 'Doktaş Dökümcülük' },
  { symbol: 'DSFNK', name: 'Destek Finans Faktoring' },
  { symbol: 'DUNYA', name: 'Dünya Holding' },
  { symbol: 'DURDO', name: 'Duran Doğan' },
  { symbol: 'DURSK', name: 'Durukan Şekerleme' },
  { symbol: 'DYOBY', name: 'DYO Boya' },
  { symbol: 'DZGYO', name: 'Deniz GYO' },
  { symbol: 'EBEBK', name: 'Ebebek Mağazacılık' },
  { symbol: 'ECILC', name: 'Eczacıbaşı İlaç' },
  { symbol: 'ECOGR', name: 'Ecogreen Enerji' },
  { symbol: 'ECZYT', name: 'Eczacıbaşı Yatırım' },
  { symbol: 'EDATA', name: 'E-Data Teknoloji' },
  { symbol: 'EDIP', name: 'Edip Gayrimenkul' },
  { symbol: 'EFOR', name: 'Efor Yatırım' },
  { symbol: 'EGEEN', name: 'Ege Endüstri' },
  { symbol: 'EGEGY', name: 'Egeyapı GYO' },
  { symbol: 'EGEPO', name: 'Ege Profil' },
  { symbol: 'EGGUB', name: 'Ege Gübre' },
  { symbol: 'EGSER', name: 'Ege Seramik' },
  { symbol: 'EKGYO', name: 'Emlak Konut GYO' },
  { symbol: 'EKOS', name: 'Ekos Teknoloji' },
  { symbol: 'EKSUN', name: 'Eksun Gıda' },
  { symbol: 'ELITE', name: 'Elite Naturel' },
  { symbol: 'EMKEL', name: 'Emek Elektrik' },
  { symbol: 'EMPA', name: 'Empa Elektronik' },
  { symbol: 'ENDA', name: 'Enda Enerji' },
  { symbol: 'ENERY', name: 'Enerya Enerji' },
  { symbol: 'ENJSA', name: 'Enerjisa Enerji' },
  { symbol: 'ENKAI', name: 'Enka İnşaat' },
  { symbol: 'ENSRI', name: 'Ensari Sinai' },
  { symbol: 'ENTRA', name: 'IC Enterra Enerji' },
  { symbol: 'EPLAS', name: 'Egeplast' },
  { symbol: 'ERBOS', name: 'Erbosan' },
  { symbol: 'ERCB', name: 'Erciyas Çelik Boru' },
  { symbol: 'EREGL', name: 'Ereğli Demir Çelik' },
  { symbol: 'ERSU', name: 'Ersu Meyve' },
  { symbol: 'ESCAR', name: 'Escar Filo' },
  { symbol: 'ESCRT', name: 'Escort Teknoloji' },
  { symbol: 'ESENBG', name: 'Esenboğa Elektrik' },
  { symbol: 'ETILR', name: 'Etiler Gıda' },
  { symbol: 'EUPWR', name: 'Europower Enerji' },
  { symbol: 'EUREN', name: 'Europen Endüstri' },
  { symbol: 'EYGYO', name: 'EYG GYO' },
  { symbol: 'FADE', name: 'Fade Gıda' },
  { symbol: 'FENER', name: 'Fenerbahçe Futbol' },
  { symbol: 'FLAP', name: 'Flap Kongre' },
  { symbol: 'FMIZP', name: 'Federal-Mogul İzmit' },
  { symbol: 'FONET', name: 'Fonet Bilgi' },
  { symbol: 'FORMT', name: 'Formet Metal' },
  { symbol: 'FORTE', name: 'Forte Bilgi' },
  { symbol: 'FRIGO', name: 'Frigo-Pak Gıda' },
  { symbol: 'FRMPS', name: 'Formül Plastik' },
  { symbol: 'FROTO', name: 'Ford Otosan' },
  { symbol: 'FZLGY', name: 'Fuzul GYO' },
  { symbol: 'GARAN', name: 'Garanti BBVA' },
  { symbol: 'GARFA', name: 'Garanti Faktoring' },
  { symbol: 'GEDIK', name: 'Gedik Yatırım' },
  { symbol: 'GEDZA', name: 'Gediz Ambalaj' },
  { symbol: 'GENIL', name: 'Gen İlaç' },
  { symbol: 'GENTS', name: 'Gentaş Kimya' },
  { symbol: 'GESAN', name: 'Gentaş Dekoratif' },
  { symbol: 'GERSA', name: 'Gersan Elektrik' },
  { symbol: 'GIREL', name: 'Girişim Elektrik' },
  { symbol: 'GIPTA', name: 'Gıpta Ofis' },
  { symbol: 'GLBMD', name: 'Global Menkul' },
  { symbol: 'GLCVY', name: 'Gelecek Varlık' },
  { symbol: 'GLRMK', name: 'Gülermak' },
  { symbol: 'GLYHO', name: 'Global Yatırım Holding' },
  { symbol: 'GMTAS', name: 'Gimat Mağazacılık' },
  { symbol: 'GOKNR', name: 'Göknur Gıda' },
  { symbol: 'GOLTS', name: 'Göltaş Çimento' },
  { symbol: 'GOODY', name: 'Goodyear' },
  { symbol: 'GOZDE', name: 'Gözde Girişim' },
  { symbol: 'GRSEL', name: 'Gür-Sel Turizm' },
  { symbol: 'GRTRK', name: 'Grainturk Holding' },
  { symbol: 'GSDDE', name: 'GSD Denizcilik' },
  { symbol: 'GSDHO', name: 'GSD Holding' },
  { symbol: 'GSRAY', name: 'Galatasaray Sportif' },
  { symbol: 'GUBRF', name: 'Gübre Fabrikaları' },
  { symbol: 'GUNDG', name: 'Gündoğdu Gıda' },
  { symbol: 'GWIND', name: 'Galata Wind' },
  { symbol: 'GZNMI', name: 'Gezinomi' },
  { symbol: 'HALKB', name: 'Halkbank' },
  { symbol: 'HATEK', name: 'Hateks' },
  { symbol: 'HATSN', name: 'Hatsan Gemi' },
  { symbol: 'HDFGS', name: 'Hedef Girişim' },
  { symbol: 'HEDEF', name: 'Hedef Holding' },
  { symbol: 'HEKTS', name: 'Hektaş' },
  { symbol: 'HKTM', name: 'Hidropar' },
  { symbol: 'HLGYO', name: 'Halk GYO' },
  { symbol: 'HOROZ', name: 'Horoz Lojistik' },
  { symbol: 'HRKET', name: 'Hareket Proje' },
  { symbol: 'HTTBT', name: 'Hitit Bilgisayar' },
  { symbol: 'HUBVC', name: 'Hub Girişim' },
  { symbol: 'HUNER', name: 'Hun Enerji' },
  { symbol: 'HURGZ', name: 'Hürriyet Gazetecilik' },
  { symbol: 'ICBCT', name: 'ICBC Turkey Bank' },
  { symbol: 'ICUGS', name: 'ICU Girişim' },
  { symbol: 'IDGYO', name: 'İdealist GYO' },
  { symbol: 'IEYHO', name: 'Işıklar Enerji Holding' },
  { symbol: 'IHAAS', name: 'İhlas Haber Ajansı' },
  { symbol: 'IHEVA', name: 'İhlas Ev Aletleri' },
  { symbol: 'IHGZT', name: 'İhlas Gazetecilik' },
  { symbol: 'IHLGM', name: 'İhlas Gayrimenkul' },
  { symbol: 'IHLAS', name: 'İhlas Holding' },
  { symbol: 'IHYAY', name: 'İhlas Yayın Holding' },
  { symbol: 'IMASM', name: 'İmas Makina' },
  { symbol: 'INDES', name: 'İndeks Bilgisayar' },
  { symbol: 'INFO', name: 'Info Yatırım' },
  { symbol: 'INGRM', name: 'Ingram Micro' },
  { symbol: 'INTEM', name: 'İntema İnşaat' },
  { symbol: 'INVEO', name: 'İnveo Yatırım' },
  { symbol: 'INVES', name: 'İnvestco Holding' },
  { symbol: 'IPEKE', name: 'TR Doğal Enerji' },
  { symbol: 'ISBIR', name: 'İşbir Sentetik' },
  { symbol: 'ISCTR', name: 'İş Bankası (C)' },
  { symbol: 'ISDMR', name: 'İskenderun Demir Çelik' },
  { symbol: 'ISFIN', name: 'İş Finansal Kiralama' },
  { symbol: 'ISGSY', name: 'İş Girişim' },
  { symbol: 'ISGYO', name: 'İş GYO' },
  { symbol: 'ISKPL', name: 'Işık Plastik' },
  { symbol: 'ISMEN', name: 'İş Yatırım Menkul' },
  { symbol: 'ISSEN', name: 'İşbir Sentetik' },
  { symbol: 'IZDEM', name: 'İzdemir Enerji' },
  { symbol: 'IZFAS', name: 'İzmir Fırça' },
  { symbol: 'IZYHO', name: 'İz Yatırım Holding' },
  { symbol: 'IZDMC', name: 'İzmir Demir Çelik' },
  { symbol: 'JANTS', name: 'Jantsa' },
  { symbol: 'KAPLM', name: 'Kaplamin Ambalaj' },
  { symbol: 'KAREL', name: 'Karel Elektronik' },
  { symbol: 'KARSN', name: 'Karsan Otomotiv' },
  { symbol: 'KARTN', name: 'Kartonsan' },
  { symbol: 'KATMR', name: 'Katmerciler' },
  { symbol: 'KAYSE', name: 'Kayseri Şeker' },
  { symbol: 'KBORU', name: 'Kuzey Boru' },
  { symbol: 'KCAER', name: 'Kocaer Çelik' },
  { symbol: 'KCHOL', name: 'Koç Holding' },
  { symbol: 'KFEIN', name: 'Kafein Yazılım' },
  { symbol: 'KGYO', name: 'Koray GYO' },
  { symbol: 'KIMMR', name: 'Ersan Alışveriş' },
  { symbol: 'KLGYO', name: 'Kiler GYO' },
  { symbol: 'KLKIM', name: 'Kalekim' },
  { symbol: 'KLMSN', name: 'Klimasan' },
  { symbol: 'KLRHO', name: 'Kiler Holding' },
  { symbol: 'KLSER', name: 'Kaleseramik' },
  { symbol: 'KLSYN', name: 'Koleksiyon Mobilya' },
  { symbol: 'KMPUR', name: 'Kalyon Güneş' },
  { symbol: 'KMTKS', name: 'Kimteks' },
  { symbol: 'KNFRT', name: 'Konfrut Gıda' },
  { symbol: 'KOCMT', name: 'Koç Metalurji' },
  { symbol: 'KONKA', name: 'Konya Kağıt' },
  { symbol: 'KONTR', name: 'Kontrolmatik' },
  { symbol: 'KONYA', name: 'Konya Çimento' },
  { symbol: 'KOPOL', name: 'Koza Polyester' },
  { symbol: 'KORDS', name: 'Kordsa' },
  { symbol: 'KOTON', name: 'Koton Mağazacılık' },
  { symbol: 'KOZAA', name: 'Koza Madencilik' },
  { symbol: 'KOZAL', name: 'Koza Altın' },
  { symbol: 'KRDMA', name: 'Kardemir (A)' },
  { symbol: 'KRDMB', name: 'Kardemir (B)' },
  { symbol: 'KRDMD', name: 'Kardemir (D)' },
  { symbol: 'KRGYO', name: 'Körfez GYO' },
  { symbol: 'KRONT', name: 'Kron Teknoloji' },
  { symbol: 'KRPLS', name: 'Koroplast' },
  { symbol: 'KRSTL', name: 'Kristal Kola' },
  { symbol: 'KRTSU', name: 'Karsu Tekstil' },
  { symbol: 'KRVGD', name: 'Kervan Gıda' },
  { symbol: 'KTLEV', name: 'Katılımevim' },
  { symbol: 'KTSKR', name: 'Kütahya Şeker' },
  { symbol: 'KUTPO', name: 'Kütahya Porselen' },
  { symbol: 'KUVVA', name: 'Kuvva Gıda' },
  { symbol: 'KUYAS', name: 'Kuyaş Yatırım' },
  { symbol: 'KZBGY', name: 'Kızılbük GYO' },
  { symbol: 'KZGYO', name: 'Kuzugrup GYO' },
  { symbol: 'LDRTR', name: 'LDR Turizm' },
  { symbol: 'LIDER', name: 'Lider Faktoring' },
  { symbol: 'LILAK', name: 'Lila Kağıt' },
  { symbol: 'LINK', name: 'Link Bilgisayar' },
  { symbol: 'LKMNH', name: 'Lokman Hekim' },
  { symbol: 'LMKDC', name: 'Limak Doğu Anadolu Çimento' },
  { symbol: 'LOGO', name: 'Logo Yazılım' },
  { symbol: 'LORAS', name: 'Loras Holding' },
  { symbol: 'LUKSK', name: 'Lüks Kadife' },
  { symbol: 'LUXGY', name: 'Luxera GYO' },
  { symbol: 'LYDHO', name: 'Lydia Holding' },
  { symbol: 'LYDYE', name: 'Lydia Yeşil Enerji' },
  { symbol: 'MAALT', name: 'Marmaris Altınyunus' },
  { symbol: 'MACKO', name: 'Mackolik' },
  { symbol: 'MAGEN', name: 'Margun Enerji' },
  { symbol: 'MAKIM', name: 'Makina Takım' },
  { symbol: 'MAKTK', name: 'Makim Makina' },
  { symbol: 'MANAS', name: 'Manas Enerji' },
  { symbol: 'MARKA', name: 'Marka Yatırım Holding' },
  { symbol: 'MARMR', name: 'Marmara Holding' },
  { symbol: 'MARTI', name: 'Martı Otel' },
  { symbol: 'MAVI', name: 'Mavi Giyim' },
  { symbol: 'MEDTR', name: 'Meditera Tıbbi' },
  { symbol: 'MEGAM', name: 'Mega Metal' },
  { symbol: 'MEKAG', name: 'Meka Global' },
  { symbol: 'MEPET', name: 'Mepet Metro' },
  { symbol: 'MERCN', name: 'Mercan Kimya' },
  { symbol: 'MERIT', name: 'Merit Turizm' },
  { symbol: 'MERKO', name: 'Merko Gıda' },
  { symbol: 'METRO', name: 'Metro Holding' },
  { symbol: 'METUR', name: 'Metropal' },
  { symbol: 'MEYSU', name: 'Meysu Gıda' },
  { symbol: 'MGROS', name: 'Migros' },
  { symbol: 'MHRGY', name: 'MHR GYO' },
  { symbol: 'MIATK', name: 'Mia Teknoloji' },
  { symbol: 'MILPA', name: 'Milpa' },
  { symbol: 'MNDRS', name: 'Menderes Tekstil' },
  { symbol: 'MNDTR', name: 'Mondi Turkey' },
  { symbol: 'MOBTL', name: 'Mobiltel' },
  { symbol: 'MOGAN', name: 'Mogan Enerji' },
  { symbol: 'MOPAS', name: 'Mopaş' },
  { symbol: 'MPARK', name: 'MLP Sağlık' },
  { symbol: 'MRGYO', name: 'Martı GYO' },
  { symbol: 'MRSHL', name: 'Marshall Boya' },
  { symbol: 'MSGYO', name: 'Mistral GYO' },
  { symbol: 'MTRKS', name: 'Matriks Finansal' },
  { symbol: 'MZHLD', name: 'Mazhar Zorlu Holding' },
  { symbol: 'NATEN', name: 'Naturel Enerji' },
  { symbol: 'NETAS', name: 'Netaş Telekomünikasyon' },
  { symbol: 'NTCAD', name: 'Netcad Yazılım' },
  { symbol: 'NIBAS', name: 'Niğbaş Beton' },
  { symbol: 'NTGAZ', name: 'Naturelgaz' },
  { symbol: 'NTHOL', name: 'Net Holding' },
  { symbol: 'NUGYO', name: 'Nurol GYO' },
  { symbol: 'NUHCM', name: 'Nuh Çimento' },
  { symbol: 'OBAMS', name: 'Oba Makarnacılık' },
  { symbol: 'OBASE', name: 'Obase Bilgisayar' },
  { symbol: 'ODAS', name: 'Odaş Elektrik' },
  { symbol: 'ODINE', name: 'Odine Solutions' },
  { symbol: 'OFISY', name: 'Ofis Yem' },
  { symbol: 'ONCSM', name: 'Oncosem Onkoloji' },
  { symbol: 'ONRYT', name: 'Onur Yüksek Teknoloji' },
  { symbol: 'ORCAY', name: 'Orçay' },
  { symbol: 'ORGE', name: 'Orge Enerji' },
  { symbol: 'OSMEN', name: 'Osmanlı Yatırım' },
  { symbol: 'OSTIM', name: 'Ostim Endüstriyel' },
  { symbol: 'OTKAR', name: 'Otokar' },
  { symbol: 'OTTO', name: 'Otto Holding' },
  { symbol: 'OYAKC', name: 'Oyak Çimento' },
  { symbol: 'OYLUM', name: 'Oylum Sinai' },
  { symbol: 'OYYAT', name: 'Oyak Yatırım' },
  { symbol: 'OZATD', name: 'Özata Denizcilik' },
  { symbol: 'OZDGY', name: 'Özderici GYO' },
  { symbol: 'OZKGY', name: 'Özak GYO' },
  { symbol: 'OZRDN', name: 'Özerden Ambalaj' },
  { symbol: 'OZSUB', name: 'Özsu Balık' },
  { symbol: 'OZYSR', name: 'Özyaşar Tel' },
  { symbol: 'PAGYO', name: 'Panora GYO' },
  { symbol: 'PAMEL', name: 'Pamel Yenilenebilir' },
  { symbol: 'PAPIL', name: 'Papilon Savunma' },
  { symbol: 'PARSN', name: 'Parsan' },
  { symbol: 'PASEU', name: 'Pasifik Eurasia' },
  { symbol: 'PASHO', name: 'Pasifik Holding' },
  { symbol: 'PASTI', name: 'Pasifik Teknoloji' },
  { symbol: 'PCILT', name: 'PC İletişim' },
  { symbol: 'PEKGY', name: 'Peker GYO' },
  { symbol: 'PENGD', name: 'Penguen Gıda' },
  { symbol: 'PENTA', name: 'Penta Teknoloji' },
  { symbol: 'PETKM', name: 'Petkim' },
  { symbol: 'PETUN', name: 'Pınar Et' },
  { symbol: 'PGSUS', name: 'Pegasus' },
  { symbol: 'PINSU', name: 'Pınar Su' },
  { symbol: 'PKART', name: 'Plastikkart' },
  { symbol: 'PKENT', name: 'Petrokent Turizm' },
  { symbol: 'PLTFM', name: 'Platform Turizm' },
  { symbol: 'PNLSN', name: 'Panelsan' },
  { symbol: 'PNSUT', name: 'Pınar Süt' },
  { symbol: 'POLHO', name: 'Polisan Holding' },
  { symbol: 'POLTK', name: 'Politeknik Metal' },
  { symbol: 'PRDGS', name: 'Pardus Girişim' },
  { symbol: 'PRKAB', name: 'Türk Prysmian Kablo' },
  { symbol: 'PRKME', name: 'Park Elektrik' },
  { symbol: 'PRZMA', name: 'Prizma Matbaacılık' },
  { symbol: 'PSDTC', name: 'Pergamon Status' },
  { symbol: 'PSGYO', name: 'Pasifik GYO' },
  { symbol: 'QNBFB', name: 'QNB Bank' },
  { symbol: 'QNBFL', name: 'QNB Finans Kiralama' },
  { symbol: 'QUAGR', name: 'QUA Granite' },
  { symbol: 'RALYH', name: 'RAL Yatırım Holding' },
  { symbol: 'RAYSG', name: 'Ray Sigorta' },
  { symbol: 'REEDR', name: 'Reeder Teknoloji' },
  { symbol: 'RNSGYO', name: 'Rönesans GYO' },
  { symbol: 'RNBOW', name: 'Rainbow Polikarbonat' },
  { symbol: 'RODRG', name: 'Rodrigo Tekstil' },
  { symbol: 'RTALB', name: 'RTA Laboratuvarları' },
  { symbol: 'RUBNS', name: 'Rubenis' },
  { symbol: 'RUZMD', name: 'Ruzy Madencilik' },
  { symbol: 'RGYAS', name: 'Reysaş GYO' },
  { symbol: 'RYSAS', name: 'Reysaş Taşımacılık' },
  { symbol: 'SAFKR', name: 'Safkar Ege' },
  { symbol: 'SAHOL', name: 'Sabancı Holding' },
  { symbol: 'SAMAT', name: 'Aray Matbaacılık' },
  { symbol: 'SANEL', name: 'San-El Mühendislik' },
  { symbol: 'SANFM', name: 'Sanifoam' },
  { symbol: 'SANKO', name: 'Sanko Pazarlama' },
  { symbol: 'SARKY', name: 'Sarkuysan' },
  { symbol: 'SASA', name: 'SASA Polyester' },
  { symbol: 'SAYAS', name: 'Say Yenilenebilir' },
  { symbol: 'SDTTR', name: 'SDT Uzay' },
  { symbol: 'SEGMN', name: 'Segmen Kardeşler' },
  { symbol: 'SEKGY', name: 'Şeker GYO' },
  { symbol: 'SEKFK', name: 'Şeker Finansal Kiralama' },
  { symbol: 'SEKUR', name: 'Sekuro Plastik' },
  { symbol: 'SELEC', name: 'Selçuk Ecza' },
  { symbol: 'SELVA', name: 'Selva Gıda' },
  { symbol: 'SERAN', name: 'Seranit' },
  { symbol: 'SEYKM', name: 'Seyitler Kimya' },
  { symbol: 'SILVR', name: 'Silverline' },
  { symbol: 'SISE', name: 'Şişecam' },
  { symbol: 'SKBNK', name: 'Şekerbank' },
  { symbol: 'SKTAS', name: 'Söktaş Tekstil' },
  { symbol: 'SKYMD', name: 'Skyalp Finansal' },
  { symbol: 'SKYMN', name: 'Şeker Yatırım' },
  { symbol: 'SMART', name: 'Smartiks Yazılım' },
  { symbol: 'SMRTG', name: 'Smart Güneş' },
  { symbol: 'SMRVK', name: 'Sümer Varlık' },
  { symbol: 'SNGYO', name: 'Sinpaş GYO' },
  { symbol: 'SNICA', name: 'Sanica Isı' },
  { symbol: 'SODSN', name: 'Söke Değirmencilik' },
  { symbol: 'SOKM', name: 'Şok Marketler' },
  { symbol: 'SONME', name: 'Sönmez Filament' },
  { symbol: 'SRVGY', name: 'Servet GYO' },
  { symbol: 'SUNTK', name: 'Sun Tekstil' },
  { symbol: 'SURGY', name: 'Sur Tatil Evleri GYO' },
  { symbol: 'SUWEN', name: 'Suwen Tekstil' },
  { symbol: 'SVGYO', name: 'Savur GYO' },
  { symbol: 'TABGD', name: 'Tab Gıda' },
  { symbol: 'TARKM', name: 'Tarkim Bitki Koruma' },
  { symbol: 'TATEP', name: 'Tatlıpınar Enerji' },
  { symbol: 'TATGD', name: 'Tat Gıda' },
  { symbol: 'TAVHL', name: 'TAV Havalimanları' },
  { symbol: 'TBORG', name: 'Türk Tuborg' },
  { symbol: 'TCELL', name: 'Turkcell' },
  { symbol: 'TCKRC', name: 'Kıraç Galvaniz' },
  { symbol: 'TDGYO', name: 'Trend GYO' },
  { symbol: 'TEKTU', name: 'Tek-Art İnşaat' },
  { symbol: 'TERA', name: 'Tera Yatırım Menkul' },
  { symbol: 'TEZOL', name: 'Europap Tezol Kağıt' },
  { symbol: 'TGSAS', name: 'TGS Dış Ticaret' },
  { symbol: 'THYAO', name: 'Türk Hava Yolları' },
  { symbol: 'TKFEN', name: 'Tekfen Holding' },
  { symbol: 'TKNSA', name: 'Teknosa' },
  { symbol: 'TLMAN', name: 'Trabzon Liman' },
  { symbol: 'TMPOL', name: 'Temapol Polimer' },
  { symbol: 'TMSN', name: 'Tümosan' },
  { symbol: 'TNZTP', name: 'Tapdi Oksijen' },
  { symbol: 'TOASO', name: 'Tofaş' },
  { symbol: 'TRGYO', name: 'Torunlar GYO' },
  { symbol: 'TRILC', name: 'Türk İlaç' },
  { symbol: 'TSGYO', name: 'TSKB GYO' },
  { symbol: 'TSKB', name: 'TSKB' },
  { symbol: 'TSPOR', name: 'Trabzonspor' },
  { symbol: 'TTKOM', name: 'Türk Telekom' },
  { symbol: 'TTRAK', name: 'Türk Traktör' },
  { symbol: 'TUCLK', name: 'Tuğçelik' },
  { symbol: 'TUKAS', name: 'Tukaş' },
  { symbol: 'TUPRS', name: 'Tüpraş' },
  { symbol: 'TUREX', name: 'Tureks Turizm' },
  { symbol: 'TURGG', name: 'Türker Proje GYO' },
  { symbol: 'TURSG', name: 'Güneş Sigorta' },
  { symbol: 'UCAYM', name: 'Uçay Mühendislik' },
  { symbol: 'UFKYT', name: 'Ufuk Yatırım' },
  { symbol: 'ULAST', name: 'Ulaşlar Turizm' },
  { symbol: 'ULKER', name: 'Ülker Bisküvi' },
  { symbol: 'ULSFA', name: 'Ulusal Faktoring' },
  { symbol: 'ULUFA', name: 'Ulusoy Elektrik' },
  { symbol: 'ULUUN', name: 'Ulusoy Un' },
  { symbol: 'UNLU', name: 'Ünlü Yatırım Holding' },
  { symbol: 'USAK', name: 'Uşak Seramik' },
  { symbol: 'UTECH', name: 'Innosa Teknoloji' },
  { symbol: 'VAKBN', name: 'Vakıfbank' },
  { symbol: 'VAKFN', name: 'Vakıf Faktoring' },
  { symbol: 'VAKKO', name: 'Vakko Tekstil' },
  { symbol: 'VANGD', name: 'Vanet Gıda' },
  { symbol: 'VBTYZ', name: 'VBT Yazılım' },
  { symbol: 'VERUS', name: 'Verusaturk GYO' },
  { symbol: 'VERUSA', name: 'Verusa Holding' },
  { symbol: 'VESBE', name: 'Vestel Beyaz Eşya' },
  { symbol: 'VESTL', name: 'Vestel' },
  { symbol: 'VKGYO', name: 'Vakıf GYO' },
  { symbol: 'VKING', name: 'Viking Kağıt' },
  { symbol: 'VRGYO', name: 'Vera Konsept GYO' },
  { symbol: 'VSNMD', name: 'Vişne Madencilik' },
  { symbol: 'YAPRK', name: 'Yaprak Süt' },
  { symbol: 'YATAS', name: 'Yataş' },
  { symbol: 'YAYLA', name: 'Yayla Enerji' },
  { symbol: 'YEOTK', name: 'Yeo Teknoloji' },
  { symbol: 'YGYO', name: 'Yeşil GYO' },
  { symbol: 'YGYO', name: 'Yeni Gimat GYO' },
  { symbol: 'YIGIT', name: 'Yiğit Akü' },
  { symbol: 'YKBNK', name: 'Yapı Kredi' },
  { symbol: 'YKSLN', name: 'Yükselen Çelik' },
  { symbol: 'YUNSA', name: 'Yunsa' },
  { symbol: 'YYLGD', name: 'Yayla Gıda' },
  { symbol: 'ZEDUR', name: 'Zedur Enerji' },
  { symbol: 'ZRGYO', name: 'Ziraat GYO' },
  { symbol: 'ZOREN', name: 'Zorlu Enerji' },
  { symbol: 'ZRGYO', name: 'Zeray GYO' },
  { symbol: 'ZGOLD', name: 'Z GYO' },
  { symbol: 'NASMD', name: 'Nasmed Sağlık' },
  { symbol: 'GULYH', name: 'Güler Yatırım Holding' },
  { symbol: 'TURCA', name: 'Turcas Holding' },
  { symbol: 'MNRDN', name: 'Tureks Turunc Madencilik' },
];

// Sektör bazlı gruplandırma
export const SECTORS: Record<string, string[]> = {
  'Bankacılık': ['AKBNK', 'GARAN', 'HALKB', 'ISCTR', 'VAKBN', 'YKBNK', 'SKBNK', 'ALBRK', 'TSKB', 'ICBCT', 'QNBFB'],
  'Holding': ['KCHOL', 'SAHOL', 'DOHOL', 'AGHOL', 'ALARK', 'GLYHO', 'NTHOL', 'POLHO', 'BERA', 'KLRHO', 'DUNYA', 'AVHOL'],
  'Havacılık & Ulaşım': ['THYAO', 'PGSUS', 'TAVHL', 'CLEBI'],
  'Otomotiv': ['FROTO', 'TOASO', 'DOAS', 'OTKAR', 'KARSN', 'ASUZU', 'TTRAK'],
  'Enerji': ['AKSEN', 'AKENR', 'AYDEM', 'AYEN', 'ENJSA', 'ZOREN', 'CWENE', 'ODAS', 'CONSE', 'ASTOR', 'PAMEL', 'GWIND', 'HUNER'],
  'Teknoloji & Yazılım': ['ASELS', 'LOGO', 'NETAS', 'ARENA', 'INDES', 'HTTBT', 'SMART', 'PAPIL', 'KFEIN', 'FONET', 'VBTYZ', 'MIATK', 'NTCAD'],
  'Perakende': ['BIMAS', 'MGROS', 'SOKM', 'BIZIM', 'TKNSA', 'MAVI', 'CRFSA', 'EBEBK', 'KOTON'],
  'Demir Çelik': ['EREGL', 'ISDMR', 'KRDMD', 'BRSAN', 'IZDMC', 'KCAER'],
  'Telekomünikasyon': ['TCELL', 'TTKOM'],
  'GYO': ['EKGYO', 'ISGYO', 'HLGYO', 'TRGYO', 'SNGYO', 'AKFGY', 'VKGYO', 'ZRGYO', 'OZKGY', 'KLGYO'],
  'Gıda': ['ULKER', 'TATGD', 'BANVT', 'PENGD', 'KNFRT', 'KRVGD', 'YYLGD', 'TABGD', 'CCOLA', 'PNSUT'],
  'Çimento': ['AKCNS', 'AFYON', 'CIMSA', 'KONYA', 'BTCIM', 'BUCIM', 'GOLTS', 'OYAKC', 'NUHCM', 'BSOKE'],
  'Sigorta': ['AKGRT', 'ANSGR', 'TURSG', 'RAYSG', 'AGESA'],
  'Savunma': ['ASELS', 'PAPIL', 'SDTTR', 'ONCSM', 'FORTE', 'ALTNM'],
  'Sağlık': ['MPARK', 'LKMNH', 'DEVA', 'ECILC', 'GENIL', 'SELEC', 'TRILC'],
};
